services:
    web:
        build: .
        environment:
          - GIT_EMAIL = "arma3server.jtf@gmail.com"
          - GIT_NAME = "${GIT_NAME}"
          - GIT_REPO = "${GIT_REPO}"
          - GIT_PASSWORD = "${GIT_PASSWORD}"