services:
    web:
        build: .
        ports:
          - "5000:5000"
        volumes:
          - ./target:/app/target
        environment:
          GIT_EMAIL: ${GIT_EMAIL}
          GIT_USERNAME: ${GIT_USERNAME}
          GIT_REPO: ${GIT_REPO}
          GIT_PASSWORD: ${GIT_PASSWORD}
          BASE_DIR: ${BASE_DIR}
          PBO_TOOL: ${PBO_TOOL}